<?php

namespace Database\Seeders;

class DemoData
{
    public static function users(): array
    {
        return [
            [
                'username' => 'kei.watanabe',
                'email' => 'kei@japantravel.com',
            ],
            [
                'username' => 'maya.kuroda',
                'email' => 'maya@japantravel.com',
            ],
            [
                'username' => 'riko.suzuki',
                'email' => 'riko@japantravel.com',
            ],
            [
                'username' => 'haru.nakamura',
                'email' => 'haru@japantravel.com',
            ],
            [
                'username' => 'yuna.tanaka',
                'email' => 'yuna@japantravel.com',
            ],
            [
                'username' => 'sora.mizuno',
                'email' => 'sora@japantravel.com',
            ],
        ];
    }

    public static function places(): array
    {
        return [
            [
                'name_id' => 'Menara Tokyo',
                'name_en' => 'Tokyo Tower',
                'description_id' => 'Menara observasi klasik di kawasan Shibakoen dengan panorama kota dan museum mini sejarah Tokyo.',
                'description_en' => 'A classic observation tower in Shibakoen with skyline views and a small Tokyo history exhibit.',
                'address' => 'Shibakoen, Minato City, Tokyo',
                'facilities' => 'Observatory Deck, Cafe, Souvenir Shop, Photo Spot',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '09:00 - 22:00',
            ],
            [
                'name_id' => 'Kuil Senso-ji',
                'name_en' => 'Senso-ji Temple',
                'description_id' => 'Kuil tertua di Asakusa dengan jalan belanja Nakamise dan suasana tradisional yang hidup.',
                'description_en' => 'Tokyo\'s oldest temple in Asakusa with the lively Nakamise shopping street.',
                'address' => 'Asakusa, Taito City, Tokyo',
                'facilities' => 'Prayer Hall, Shopping Street, Rest Area, Info Center',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '06:00 - 17:00',
            ],
            [
                'name_id' => 'Kuil Meiji Jingu',
                'name_en' => 'Meiji Jingu Shrine',
                'description_id' => 'Kuil besar yang tenang di tengah hutan kota, cocok untuk rehat dari keramaian Tokyo.',
                'description_en' => 'A serene shrine set in a city forest, ideal for a calm break from Tokyo\'s bustle.',
                'address' => 'Harajuku, Shibuya City, Tokyo',
                'facilities' => 'Forest Path, Prayer Hall, Rest Area, Souvenir Corner',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '05:00 - 18:00',
            ],
            [
                'name_id' => 'Shibuya Crossing',
                'name_en' => 'Shibuya Crossing',
                'description_id' => 'Simpang pejalan kaki tersibuk dengan neon dan pusat belanja modern di sekitarnya.',
                'description_en' => 'The busiest pedestrian crossing framed by neon lights and modern shopping hubs.',
                'address' => 'Shibuya City, Tokyo',
                'facilities' => 'Photo Spot, Shopping, Cafes, Observation Points',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '24 Jam',
            ],
            [
                'name_id' => 'Taman Ueno',
                'name_en' => 'Ueno Park',
                'description_id' => 'Taman kota luas dengan museum, kebun binatang, dan spot piknik musiman.',
                'description_en' => 'A spacious city park with museums, a zoo, and seasonal picnic spots.',
                'address' => 'Ueno, Taito City, Tokyo',
                'facilities' => 'Museum Access, Picnic Area, Zoo, Pond',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '05:00 - 23:00',
            ],
            [
                'name_id' => 'Pasar Tsukiji Outer',
                'name_en' => 'Tsukiji Outer Market',
                'description_id' => 'Surga kuliner pagi dengan pilihan seafood segar dan jajanan pasar khas Jepang.',
                'description_en' => 'Morning food haven with fresh seafood and classic market snacks.',
                'address' => 'Tsukiji, Chuo City, Tokyo',
                'facilities' => 'Food Stalls, Rest Area, Guided Tours, Cashless Booths',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '07:00 - 14:00',
            ],
            [
                'name_id' => 'Taman Pantai Odaiba',
                'name_en' => 'Odaiba Seaside Park',
                'description_id' => 'Tepi pantai buatan dengan pemandangan jembatan dan skyline Tokyo.',
                'description_en' => 'A man-made beach with views of the bridge and Tokyo skyline.',
                'address' => 'Odaiba, Minato City, Tokyo',
                'facilities' => 'Seaside Walk, Photo Spot, Rest Area, Bike Rental',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '05:00 - 23:00',
            ],
            [
                'name_id' => 'Kuil Fushimi Inari',
                'name_en' => 'Fushimi Inari Shrine',
                'description_id' => 'Ribuan torii merah membentuk jalur mendaki menuju puncak Gunung Inari.',
                'description_en' => 'Thousands of red torii gates create a hiking trail up Mount Inari.',
                'address' => 'Fushimi Ward, Kyoto',
                'facilities' => 'Torii Trail, Rest Area, Prayer Spot, Souvenir Shop',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '24 Jam',
            ],
            [
                'name_id' => 'Kuil Kiyomizu-dera',
                'name_en' => 'Kiyomizu-dera Temple',
                'description_id' => 'Kuil kayu berteras luas dengan panorama kota Kyoto dan nuansa klasik.',
                'description_en' => 'A wooden temple with a wide terrace and panoramic Kyoto views.',
                'address' => 'Higashiyama, Kyoto',
                'facilities' => 'Observation Terrace, Tea Shop, Rest Area, Photo Spot',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '06:00 - 18:00',
            ],
            [
                'name_id' => 'Kuil Kinkaku-ji',
                'name_en' => 'Kinkaku-ji Temple',
                'description_id' => 'Paviliun emas yang memantul di kolam, salah satu ikon Kyoto.',
                'description_en' => 'A golden pavilion reflected on a pond, one of Kyoto\'s icons.',
                'address' => 'Kita Ward, Kyoto',
                'facilities' => 'Zen Garden, Souvenir Shop, Tea House, Rest Area',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '09:00 - 17:00',
            ],
            [
                'name_id' => 'Hutan Bambu Arashiyama',
                'name_en' => 'Arashiyama Bamboo Grove',
                'description_id' => 'Lorong bambu yang sejuk dengan jalur pejalan kaki dan rickshaw.',
                'description_en' => 'Cool bamboo lanes with walking paths and rickshaw rides.',
                'address' => 'Arashiyama, Kyoto',
                'facilities' => 'Walking Path, Photo Spot, Rickshaw Ride, Rest Area',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '24 Jam',
            ],
            [
                'name_id' => 'Gang Hanamikoji Gion',
                'name_en' => 'Gion Hanamikoji Street',
                'description_id' => 'Jalan bersejarah geisha dengan rumah teh tradisional dan suasana elegan.',
                'description_en' => 'Historic geisha street lined with tea houses and elegant ambience.',
                'address' => 'Gion, Kyoto',
                'facilities' => 'Cultural Walk, Photo Spot, Tea House, Guided Tour',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '09:00 - 22:00',
            ],
            [
                'name_id' => 'Kastil Osaka',
                'name_en' => 'Osaka Castle',
                'description_id' => 'Kastil megah dengan taman luas dan museum sejarah di dalamnya.',
                'description_en' => 'A grand castle with large gardens and a history museum inside.',
                'address' => 'Chuo Ward, Osaka',
                'facilities' => 'Museum, Garden, Observation Deck, Souvenir Shop',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '09:00 - 17:00',
            ],
            [
                'name_id' => 'Dotonbori',
                'name_en' => 'Dotonbori',
                'description_id' => 'Distrik kuliner malam dengan papan neon dan jajanan kaki lima legendaris.',
                'description_en' => 'Nighttime food district with neon signs and legendary street snacks.',
                'address' => 'Chuo Ward, Osaka',
                'facilities' => 'Food Street, Photo Spot, Shopping, River Walk',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '10:00 - 00:00',
            ],
            [
                'name_id' => 'Taman Nara',
                'name_en' => 'Nara Park',
                'description_id' => 'Taman luas dengan rusa jinak, kuil, dan jalur jalan kaki.',
                'description_en' => 'A spacious park with friendly deer, temples, and walking trails.',
                'address' => 'Nara, Nara Prefecture',
                'facilities' => 'Deer Feeding, Walking Trail, Temple Access, Picnic Area',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '06:00 - 22:00',
            ],
            [
                'name_id' => 'Kastil Himeji',
                'name_en' => 'Himeji Castle',
                'description_id' => 'Kastil putih berlapis yang terawat, dikenal sebagai White Heron Castle.',
                'description_en' => 'A well-preserved white castle known as the White Heron Castle.',
                'address' => 'Himeji, Hyogo',
                'facilities' => 'Castle Museum, Garden, Photo Spot, Guided Tour',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '09:00 - 17:00',
            ],
            [
                'name_id' => 'Taman Perdamaian Hiroshima',
                'name_en' => 'Hiroshima Peace Memorial Park',
                'description_id' => 'Ruang refleksi dengan museum perdamaian dan monumen bersejarah.',
                'description_en' => 'A reflective space with the peace museum and historic monuments.',
                'address' => 'Naka Ward, Hiroshima',
                'facilities' => 'Museum, Memorial, Rest Area, Guided Tour',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '08:30 - 18:00',
            ],
            [
                'name_id' => 'Kuil Itsukushima',
                'name_en' => 'Itsukushima Shrine',
                'description_id' => 'Gerbang torii di atas air yang ikonik di Pulau Miyajima.',
                'description_en' => 'An iconic floating torii gate on Miyajima Island.',
                'address' => 'Miyajima, Hiroshima',
                'facilities' => 'Shrine Complex, Ferry Access, Photo Spot, Rest Area',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '06:30 - 17:30',
            ],
            [
                'name_id' => 'Stasiun 5 Gunung Fuji',
                'name_en' => 'Mount Fuji 5th Station',
                'description_id' => 'Titik awal pendakian populer dengan udara sejuk dan pemandangan danau.',
                'description_en' => 'A popular hiking starting point with cool air and lake views.',
                'address' => 'Fujiyoshida, Yamanashi',
                'facilities' => 'Hiking Start, Rest Area, Souvenir Shop, View Deck',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '08:00 - 18:00',
            ],
            [
                'name_id' => 'Danau Kawaguchi',
                'name_en' => 'Lake Kawaguchi',
                'description_id' => 'Danau tenang dengan latar Gunung Fuji, cocok untuk foto pagi.',
                'description_en' => 'A tranquil lake with Mount Fuji views, perfect for morning photos.',
                'address' => 'Fujikawaguchiko, Yamanashi',
                'facilities' => 'Lakeside Walk, Boat Ride, Photo Spot, Cafe',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '06:00 - 19:00',
            ],
            [
                'name_id' => 'Taman Monyet Jigokudani',
                'name_en' => 'Jigokudani Snow Monkey Park',
                'description_id' => 'Habitat monyet salju yang berendam di onsen alami pada musim dingin.',
                'description_en' => 'Home of snow monkeys soaking in natural hot springs in winter.',
                'address' => 'Yamanouchi, Nagano',
                'facilities' => 'Walking Trail, Observation Area, Rest Area, Cafe',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '09:00 - 16:00',
            ],
            [
                'name_id' => 'Taman Kenroku-en',
                'name_en' => 'Kenroku-en Garden',
                'description_id' => 'Taman lanskap klasik dengan kolam, jembatan batu, dan musim yang berwarna.',
                'description_en' => 'A classic landscape garden with ponds, stone bridges, and seasonal colors.',
                'address' => 'Kanazawa, Ishikawa',
                'facilities' => 'Garden Walk, Tea House, Photo Spot, Rest Area',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '07:00 - 18:00',
            ],
            [
                'name_id' => 'Desa Shirakawa-go',
                'name_en' => 'Shirakawa-go Village',
                'description_id' => 'Desa tradisional dengan rumah atap gassho yang khas di lembah pegunungan.',
                'description_en' => 'Traditional village with gassho-roof houses in a mountain valley.',
                'address' => 'Ono District, Gifu',
                'facilities' => 'Cultural Village, Viewpoint, Museum, Rest Area',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '08:30 - 17:30',
            ],
            [
                'name_id' => 'Kota Tua Takayama',
                'name_en' => 'Takayama Old Town',
                'description_id' => 'Kawasan kota tua dengan toko kayu, sake brewery, dan pasar pagi.',
                'description_en' => 'Old town area with wooden shops, sake breweries, and morning markets.',
                'address' => 'Takayama, Gifu',
                'facilities' => 'Historical Walk, Market, Souvenir Shop, Cafe',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '08:00 - 18:00',
            ],
            [
                'name_id' => 'Kanal Otaru',
                'name_en' => 'Otaru Canal',
                'description_id' => 'Kanal romantis dengan gudang bata dan kafe kecil di Hokkaido.',
                'description_en' => 'A romantic canal lined with brick warehouses and small cafes in Hokkaido.',
                'address' => 'Otaru, Hokkaido',
                'facilities' => 'Canal Walk, Cafe, Photo Spot, Boat Tour',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '08:00 - 22:00',
            ],
            [
                'name_id' => 'Taman Odori Sapporo',
                'name_en' => 'Sapporo Odori Park',
                'description_id' => 'Taman kota pusat festival musiman dengan area hijau yang luas.',
                'description_en' => 'City park hosting seasonal festivals with wide green spaces.',
                'address' => 'Chuo Ward, Sapporo',
                'facilities' => 'Festival Grounds, Picnic Area, Food Stalls, Rest Area',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '06:00 - 23:00',
            ],
            [
                'name_id' => 'Panorama Malam Hakodate',
                'name_en' => 'Hakodate Night View',
                'description_id' => 'Pemandangan malam spektakuler dari Gunung Hakodate.',
                'description_en' => 'Spectacular night view from Mount Hakodate.',
                'address' => 'Hakodate, Hokkaido',
                'facilities' => 'Observation Deck, Ropeway, Photo Spot, Cafe',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '10:00 - 22:00',
            ],
            [
                'name_id' => 'Pemandian Air Panas Beppu',
                'name_en' => 'Beppu Hot Springs',
                'description_id' => 'Kawasan onsen dengan banyak sumber air panas dan spa tradisional.',
                'description_en' => 'Onsen area with multiple hot springs and traditional spa experiences.',
                'address' => 'Beppu, Oita',
                'facilities' => 'Onsen, Spa, Rest Area, Souvenir Shop',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '09:00 - 21:00',
            ],
            [
                'name_id' => 'Akuarium Churaumi Okinawa',
                'name_en' => 'Okinawa Churaumi Aquarium',
                'description_id' => 'Akuarium besar dengan tangki hiu paus dan ekosistem laut tropis.',
                'description_en' => 'Large aquarium featuring whale sharks and tropical marine ecosystems.',
                'address' => 'Motobu, Okinawa',
                'facilities' => 'Aquarium, Cafe, Gift Shop, Kids Area',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '08:30 - 19:00',
            ],
            [
                'name_id' => 'Pulau Seni Naoshima',
                'name_en' => 'Naoshima Art Island',
                'description_id' => 'Pulau kecil yang dipenuhi museum seni kontemporer dan instalasi luar ruang.',
                'description_en' => 'Small island packed with contemporary museums and outdoor installations.',
                'address' => 'Naoshima, Kagawa',
                'facilities' => 'Art Museum, Bike Rental, Cafe, Guided Tour',
                'open_days' => 'Senin - Minggu',
                'open_hours' => '09:00 - 18:00',
            ],
        ];
    }

    public static function regions(): array
    {
        return [
            ['id' => 'Kyoto', 'en' => 'Kyoto'],
            ['id' => 'Tokyo', 'en' => 'Tokyo'],
            ['id' => 'Osaka', 'en' => 'Osaka'],
            ['id' => 'Hokkaido', 'en' => 'Hokkaido'],
            ['id' => 'Fukuoka', 'en' => 'Fukuoka'],
        ];
    }

    public static function souvenirTypes(): array
    {
        return [
            [
                'name_id' => 'Kue Matcha',
                'name_en' => 'Matcha Cookies',
                'desc_id' => 'Kue renyah dengan matcha halus, dipanggang dengan resep :region untuk aroma hijau yang lembut.',
                'desc_en' => 'Crisp cookies with smooth matcha, baked in a :region style for a soft green aroma.',
                'price' => [45000, 110000],
                'stock' => [20, 80],
            ],
            [
                'name_id' => 'Mochi Kacang Merah',
                'name_en' => 'Red Bean Mochi',
                'desc_id' => 'Mochi lembut dengan isian kacang merah manis khas :region.',
                'desc_en' => 'Soft mochi with sweet red bean filling inspired by :region.',
                'price' => [50000, 120000],
                'stock' => [18, 60],
            ],
            [
                'name_id' => 'Teh Sakura',
                'name_en' => 'Sakura Tea',
                'desc_id' => 'Teh bunga sakura dengan aroma lembut yang populer untuk oleh-oleh :region.',
                'desc_en' => 'Sakura blossom tea with a gentle aroma, popular as a :region souvenir.',
                'price' => [65000, 150000],
                'stock' => [25, 70],
            ],
            [
                'name_id' => 'Cokelat Nama',
                'name_en' => 'Nama Chocolate',
                'desc_id' => 'Cokelat lembut yang meleleh, dibuat dengan gaya patisserie :region.',
                'desc_en' => 'Smooth, melt-in-your-mouth chocolate crafted in a :region patisserie style.',
                'price' => [85000, 180000],
                'stock' => [15, 55],
            ],
            [
                'name_id' => 'Keripik Rumput Laut',
                'name_en' => 'Seaweed Chips',
                'desc_id' => 'Keripik rumput laut gurih dengan bumbu laut dari :region.',
                'desc_en' => 'Savory seaweed chips seasoned with coastal flavors from :region.',
                'price' => [40000, 90000],
                'stock' => [30, 90],
            ],
            [
                'name_id' => 'Biskuit Mentega',
                'name_en' => 'Butter Biscuits',
                'desc_id' => 'Biskuit mentega yang renyah dengan sentuhan rasa khas :region.',
                'desc_en' => 'Crisp butter biscuits with a signature :region twist.',
                'price' => [45000, 100000],
                'stock' => [20, 70],
            ],
            [
                'name_id' => 'Selai Yuzu',
                'name_en' => 'Yuzu Spread',
                'desc_id' => 'Selai yuzu segar yang cocok untuk roti dan dessert ala :region.',
                'desc_en' => 'Bright yuzu spread for bread and desserts in a :region style.',
                'price' => [60000, 140000],
                'stock' => [18, 60],
            ],
            [
                'name_id' => 'Bumbu Ramen Shoyu',
                'name_en' => 'Shoyu Ramen Seasoning',
                'desc_id' => 'Bumbu ramen shoyu siap masak dengan rasa kedelai khas :region.',
                'desc_en' => 'Ready-to-cook shoyu ramen seasoning with :region soy flavor.',
                'price' => [55000, 120000],
                'stock' => [20, 60],
            ],
            [
                'name_id' => 'Granola Ume',
                'name_en' => 'Ume Granola',
                'desc_id' => 'Granola dengan sentuhan ume asam manis favorit traveler :region.',
                'desc_en' => 'Granola with sweet-sour ume notes loved by :region travelers.',
                'price' => [50000, 110000],
                'stock' => [22, 65],
            ],
            [
                'name_id' => 'Tenugui Motif',
                'name_en' => 'Patterned Tenugui',
                'desc_id' => 'Kain tenugui motif tradisional dengan palet warna khas :region.',
                'desc_en' => 'Traditional tenugui cloth with :region-inspired color palettes.',
                'price' => [70000, 160000],
                'stock' => [15, 45],
            ],
            [
                'name_id' => 'Kipas Lipat Sensu',
                'name_en' => 'Sensu Folding Fan',
                'desc_id' => 'Kipas lipat ringan dengan motif elegan dari studio :region.',
                'desc_en' => 'Light folding fan with elegant motifs from a :region studio.',
                'price' => [90000, 180000],
                'stock' => [15, 40],
            ],
            [
                'name_id' => 'Dompet Koin Gamaguchi',
                'name_en' => 'Gamaguchi Coin Purse',
                'desc_id' => 'Dompet koin dengan kunci khas gamaguchi, populer di toko :region.',
                'desc_en' => 'Coin purse with a gamaguchi clasp, popular in :region boutiques.',
                'price' => [65000, 150000],
                'stock' => [18, 50],
            ],
            [
                'name_id' => 'Catatan Washi',
                'name_en' => 'Washi Notebook',
                'desc_id' => 'Buku catatan kertas washi yang halus, dibuat di workshop :region.',
                'desc_en' => 'Smooth washi paper notebook crafted in a :region workshop.',
                'price' => [50000, 120000],
                'stock' => [20, 60],
            ],
            [
                'name_id' => 'Set Pulpen Gel',
                'name_en' => 'Gel Pen Set',
                'desc_id' => 'Set pulpen gel dengan tinta stabil, favorit pelajar :region.',
                'desc_en' => 'Gel pen set with consistent ink flow, a :region student favorite.',
                'price' => [45000, 90000],
                'stock' => [25, 70],
            ],
            [
                'name_id' => 'Aromaterapi Hinoki',
                'name_en' => 'Hinoki Aroma Sachet',
                'desc_id' => 'Aroma hinoki menenangkan untuk kamar dan koper perjalanan :region.',
                'desc_en' => 'Calming hinoki aroma for rooms and travel bags inspired by :region.',
                'price' => [60000, 140000],
                'stock' => [18, 50],
            ],
            [
                'name_id' => 'Mug Keramik',
                'name_en' => 'Ceramic Mug',
                'desc_id' => 'Mug keramik dengan glaze hangat yang dibuat di studio :region.',
                'desc_en' => 'Ceramic mug with warm glaze crafted in a :region studio.',
                'price' => [90000, 200000],
                'stock' => [12, 40],
            ],
        ];
    }

    public static function reviewTemplates(): array
    {
        return [
            ['rating' => 5, 'comment' => 'Tempatnya bersih dan nyaman, fotonya bagus sekali.'],
            ['rating' => 4, 'comment' => 'Ramai tapi teratur, suasananya tetap enak dinikmati.'],
            ['rating' => 5, 'comment' => 'Pengalaman terbaik selama trip, bakal kembali lagi.'],
            ['rating' => 3, 'comment' => 'Bagus, tapi perlu datang lebih pagi agar lebih tenang.'],
            ['rating' => 4, 'comment' => 'Akses transportasi mudah dan fasilitasnya lengkap.'],
            ['rating' => 5, 'comment' => 'Spot foto favorit, view-nya luar biasa terutama saat senja.'],
            ['rating' => 4, 'comment' => 'Area cukup luas, cocok untuk jalan santai seharian.'],
            ['rating' => 5, 'comment' => 'Wajib masuk itinerary, vibes Jepang klasiknya terasa.'],
            ['rating' => 4, 'comment' => 'Staff ramah dan informasi di lokasi jelas.'],
            ['rating' => 3, 'comment' => 'Antriannya panjang, tapi worth it untuk dilihat.'],
        ];
    }

    public static function souvenirs(): array
    {
        mt_srand(2025);
        $souvenirs = [];
        foreach (self::souvenirTypes() as $type) {
            foreach (self::regions() as $region) {
                $souvenirs[] = [
                    'name_id' => $type['name_id'] . ' ' . $region['id'],
                    'name_en' => $region['en'] . ' ' . $type['name_en'],
                    'description_id' => str_replace(':region', $region['id'], $type['desc_id']),
                    'description_en' => str_replace(':region', $region['en'], $type['desc_en']),
                    'price' => mt_rand($type['price'][0], $type['price'][1]),
                    'stock' => mt_rand($type['stock'][0], $type['stock'][1]),
                ];
            }
        }

        return $souvenirs;
    }
}
